version: '3.8'

services:
  laravel_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor  
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:8BxonopK3DQsz416tVHpt0Llr1uubH4aTkwPceJq2So=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=prueba
      - DB_USERNAME=root
      - DB_PASSWORD=123
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped

  react_frontend:
    build:
      context: ./reactFront
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000" 
    volumes:
      - ./reactFront:/usr/src/app
      - /usr/src/app/node_modules
      - ./reactFront/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: prueba
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
